### ISSUE TITLE
Right click to use the bed while jumping ==> Steve goes to long sleep

### ISSUE THREAD

**Issue by pixie-grasper** [kingrunes/Somnia#22]
I'm using Somnia 1.3.1.16 on the Minecraft 1.7.10 (Because the 1.4.1.23 doesn't work in my env).
I've noticed Steve wakes up 2 times every day (when he has not the clock), and I've also noticed the wake-up system doesn't work once in a while.
Finally I've gotten he doesn't wake up in a day when use the bed in jumping.

Thank you for reading.

**Comment by kingrunes** [comment]
The #23 build was known to be broken, as you said it doesn't work. Thr latest build for 1.7.10 is actually labelled as the last official 1.7.10 build on the Jenkins build system. There is a link to Jenkins on the somnia minecraftforums thread. I'm sure this build will fix the wake up problems as I've changed a lot since 1.3.1.16

**Comment by pixie-grasper** [comment]
Thank your comment, let's see... Is the link (http://www.codeheist.net:8080/job/Somnia/) the Jenkins?

Thank you, I've tried that. Then, the labelled #32 build also has the problem. However, a very long time simulate is convenient for me because of quarry, mass-fabricator, gregtech, and so on.
Summary, It's not fixed but I think you hasn't to fix.

**Comment by kingrunes** [comment]
That's an interesting bug... I'll try to recreate it now.

**Comment by kingrunes** [comment]
I can't recreate that. The wake-up seems to work as intended.

Can you explain in more detail how you are able to reproduce this extended sleep bug?
